# Generated by Django 4.1.13 on 2025-09-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('cod', 'Pay by Cash')], max_length=10),
        ),
    ]
